admins:
- lucydot
choochoo_branch: main
gh-pages: false
gh-pages_branch: gh-pages
instructors:
- lucydot
- choochoo-bot
- choochoo-bot
project_repo: lucydot/ChooChoo
project_title: Choochoo template repository
questions: true
students:
- choochoo-bot
- lucydot
votes_required: 8
web_address: lucydot.github.io/ChooChoo
